using System.Text;

namespace Aspire.Hosting.Komodo;

/// <summary>Renders a Komodo Resource-Sync TOML <c>[[stacks]]</c> block with the compose inlined.</summary>
internal static class KomodoResyncToml
{
    public static string Render(string stackName, string serverName, string composeYaml)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Aspire.Hosting.Komodo via `aspire publish`.");
        sb.AppendLine("# Point a Komodo Resource Sync at this file (or the directory) to apply it.");
        sb.AppendLine();
        sb.AppendLine("[[stacks]]");
        sb.AppendLine($"name = \"{EscapeBasic(stackName)}\"");
        sb.AppendLine("deploy = true");
        sb.AppendLine();
        sb.AppendLine("[stacks.config]");
        sb.AppendLine($"server = \"{EscapeBasic(serverName)}\"");
        sb.AppendLine("files_on_host = false");
        var compose = composeYaml.TrimEnd('\n');
        if (!compose.Contains("'''", StringComparison.Ordinal))
        {
            // TOML multiline literal string — no escaping, embeds the compose verbatim.
            sb.AppendLine("file_contents = '''");
            sb.Append(compose);
            sb.Append('\n');
            sb.AppendLine("'''");
        }
        else
        {
            // The compose contains the literal-string delimiter, which a '''…''' block can't hold.
            // Fall back to a multiline BASIC string, escaping its two metacharacters (\ and ").
            var escaped = compose.Replace("\\", "\\\\", StringComparison.Ordinal)
                                 .Replace("\"\"\"", "\\\"\\\"\\\"", StringComparison.Ordinal);
            sb.AppendLine("file_contents = \"\"\"");
            sb.Append(escaped);
            sb.Append('\n');
            sb.AppendLine("\"\"\"");
        }
        return sb.ToString();
    }

    // Escape a string for a TOML basic ("…") string: backslash, quote, and control chars.
    private static string EscapeBasic(string s) => s
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal)
        .Replace("\n", "\\n", StringComparison.Ordinal)
        .Replace("\r", "\\r", StringComparison.Ordinal)
        .Replace("\t", "\\t", StringComparison.Ordinal);
}
